USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_CheckStkExists]    Script Date: 9/10/2021 4:15:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_CheckStkExists]
@SOTK nchar(9)
AS
BEGIN
	
	IF EXISTS (SELECT 1 FROM DBO.TaiKhoan WHERE DBO.TaiKhoan.SOTK = @SOTK) 
	BEGIN
		RETURN 1;
	END

	IF EXISTS (SELECT 1 FROM LINK1.NGANHANG.DBO.TaiKhoan TK WHERE TK.SOTK = @SOTK) 
	BEGIN
		RETURN 1;
	END

	RETURN 0;
END
GO

