USE [NganHang]
GO

/****** Object:  StoredProcedure [dbo].[SP_CHECKKHEXISTS]    Script Date: 11/11/2021 10:06:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_CHECKKHEXISTS]
@CMND NCHAR(10)
AS
BEGIN
	
	IF EXISTS (SELECT 1 FROM DBO.KhachHang WHERE DBO.KhachHang.CMND = @CMND) 
	BEGIN
		RETURN 1;
	END

	IF EXISTS (SELECT 1 FROM LINK2.NganHang.DBO.KhachHang KH WHERE KH.CMND = @CMND) 
	BEGIN
		RETURN 1;
	END

	RETURN 0;
END
GO

