USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_CHECKNVEXISTS]    Script Date: 9/10/2021 4:15:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_CHECKNVEXISTS]
@MANV NVARCHAR(10)
AS
BEGIN
	
	IF EXISTS (SELECT 1 FROM DBO.NhanVien WHERE DBO.NhanVien.MANV = @MANV) 
	BEGIN
		RETURN 1;
	END

	IF EXISTS (SELECT 1 FROM LINK1.NGANHANG.DBO.NhanVien NV WHERE NV.MANV = @MANV) 
	BEGIN
		RETURN 1;
	END

	RETURN 0;
END
GO

