USE [NganHang]
GO

/****** Object:  StoredProcedure [dbo].[SP_TRACUUKH]    Script Date: 11/24/2021 11:58:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_TRACUUKH]
@CMND NCHAR(10)
AS
BEGIN
	IF EXISTS (SELECT 1 FROM DBO.KhachHang WHERE DBO.KhachHang.CMND = @CMND) 
	BEGIN
		RETURN 1;
	END
	ELSE IF EXISTS (SELECT 1 FROM LINK1.NganHang.DBO.KhachHang KH WHERE KH.CMND = @CMND) 
	BEGIN
		RETURN 1;
	END

	RETURN 0;
END
GO

