USE [NGANHANG]
GO

/****** Object:  View [dbo].[V_DS_NHANVIEN]    Script Date: 16/09/2021 11:55:40 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[V_DS_NHANVIEN] AS
SELECT MANV, CONCAT(HO, ' ', TEN) as HOTEN
FROM NHANVIEN 
WHERE TrangThaiXoa = 0 AND NOT EXISTS(SELECT SUSER_SNAME(sid) FROM sys.sysusers WHERE name = CAST(MANV AS VARCHAR))

GO

